id: IED18DDBB
source: https://sakyaresearch.org
source_file: null
initial_creation_type: input
imported: '2022-06-19T14:20:23.130537'
last_modified: '2022-06-19T14:20:23.130550'
parser: null
source_metadata:
  title: Hagiography of mTshal min bSod nams bzang po (1341–1433)
  author: ཡོན་ཏན་བཟང་པོ།
  description: 'Digital version 1.0 {Tibetan}; master xml (completed: 2013-04); revision
    in process, thematic TEI markup'
  file_info:
  - 'Language: Tibetan'
  - 'Coverage: Full Text'
  - 'Accessible: publicly'
  responibilities:
  - Digital edition:ས་སྐྱ་ཞིབ་འཇུག་ཁང་། (src)
  - Text input:Lobsang Gyaltsen (Dharamsala) (lg)
  - Editorial process:Mathias Fermer (mf)
  - TEI Encoding:ས་སྐྱ་ཞིབ་འཇུག་ཁང་།
  - TEI Markup:Mathias Fermer (mf)
  - Revisions/Corrections:Lobsang Gyaltsen (lg)
  text_witnesses: https://sakyaresearch.org/sources/504
  bases:
    011c:
      title: Hagiography of mTshal min bSod nams bzang po (1341–1433)
      order: 1
      base_file: 011c.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
